package it.polimi.ingsw.view;

public enum ReceivedViewState {
    BOARD_VIEW_STATE ,
    CHALLENGER_SELECTION_VIEW_STATE,
    GOD_POWER_VIEW_STATE,
    LOGIN_VIEW_STATE,
    VIEW_STATE3_D,
    WAITING_VIEW_STATE,
    WORKER_SETUP_VIEW_STATE;
}
